### ISSUE TITLE
throw new TypeError('Invalid binary format')

### ISSUE THREAD

**Issue by tungnnt** [AngaBlue/exe#10]
**Describe the bug**
I cannot build my application with your lib
![image](https://github.com/AngaBlue/exe/assets/56547878/e76530c0-6965-49e6-b056-1a64186f27c9)

**To Reproduce**
The config was showed in the above picture

**Expected behavior**
The build should be processed

**Additional context**
I bundle with additional asset, it can be configed via `assets` in `package.json` when [using](https://github.com/vercel/pkg?tab=readme-ov-file#assets )`pkg`, but I don't find where to add assets using this lib

**Comment by AngaBlue** [comment]
Hi, thanks for the report!  Can you please show me the arguments you are passing to the build function?  I am unable to reproduce this issue with what you've provided so far.

**Comment by tungnnt** [comment]
Yes, I code application using Nestjs server template
```
const exe = require("@angablue/exe");

const build = exe({
  entry: "dist/main.js",
  out: "./build/My Cool App.exe",
  pkg: ["--compress", "Brotli"],
  version: "2.4.2",
  target: "latest-win-x64",
  icon: "./assets/icon.ico", // Application icons must be in .ico format
  executionLevel: "asInvoker",
  properties: {
    FileDescription: "My Cool App",
    ProductName: "My Cool App",
    LegalCopyright: "AngaBlue https://anga.blue",
    OriginalFilename: "My Cool App.exe",
  },
});

build.then(() => console.log("Build completed!"));
```

**Comment by AngaBlue** [comment]
I have updated the `resedit` package that is used internally by `@angablue/exe` with version `v2.1.3`.  This addresses some bugs that could be corrupting your output.  Does this update resolve your problem?
