### ISSUE TITLE
Custom the Company value while hover on EXE

### ISSUE THREAD

**Issue by xunziheng** [AngaBlue/exe#11]
**Describe the bug**
nice lib! so can we custom the Company value?
![image](https://github.com/AngaBlue/exe/assets/35691153/594e8dcb-9ad7-457d-b1aa-3d52c1c0c7e5)

**To Reproduce**

**Expected behavior**
custom Company value

**Additional context**
none

**Comment by AngaBlue** [comment]
Hi @xunziheng,
Thanks for the suggestion!  I'll look into it.
