### ISSUE TITLE
Issues with warning suppression and ncc

### ISSUE THREAD

**Issue by koga73** [AngaBlue/exe#15]
Hi, see my notes below:

1. Errors with CommonJS due to injected warning suppression code. Is the warning suppression code necessary? Previously the flag "disableExperimentalSEAWarning" fixed this issue. Also the warning suppression code seems prone to breaking if Node changes the error message.

2. Errors with hashbang in entry file `#!/usr/bin/env node`. I have this line at the top of my CLI application and the tool is now erroring on it due to the injected warning suppression code being added before this line.

3. Option to turn off ncc? I am already using webpack to bundle my application and would like to generate the executable with my webpack bundle as the entry.

Thanks!

**Comment by AngaBlue** [comment]
Hi again!

1. Unfortunately, "disableExperimentalSEAWarning" does not disable all warnings related to SEA across all versions of node (I tested v20, v21 & v22).  As mentioned in #14 , there is a warning about `require()` too.  The `disableExperimentalSEAWarning` is still being used too.  With regards to the fragility of the warning suppression code - I agree, however, having tried multiple other potential solutions such as overriding `process.emitWarning`, I was unable to successfully suppress the warnings.  If you find an alternate/more robust method I'd be happy to drop that in.

2. I did not think about this case.  I'll fix that with the next patch.

3. Understood, does running `ncc` with the webpack cause any issues or is it just extra time during the build?

**Comment by AngaBlue** [comment]
I have addressed point 2 in #16 .  What were the other errors you were facing in relation to error suppression?

**Comment by koga73** [comment]
Ok finally got back to this and identified a few issues:

1. "useCodeCache: - according to the Node docs: "Note: import() does not work when useCodeCache is true."
https://nodejs.org/api/single-executable-applications.html#v8-code-cache-support
Can this be removed?

2. As for webpack + ncc, it does take longer and it would be nice to have ncc as optional since there are so many other popular build tools such as Webpack and Vite.

3. In index.ts the "signtool" line needs an "await"

I can make a PR if you'd like, but as all of the items are minimal I figured it would be easier to just open an issue.
Thank you!!

**Comment by AngaBlue** [comment]
I've implemented all these points and released them in `v3.1.0`.  Hopefully this solves the issues you were having.  Thank you for your report!  I'll keep this issue open until you can confirm that the fix works.

**Comment by koga73** [comment]
Works now for me, thank you!
