### ISSUE TITLE
cannot support package.json config for pkg

### ISSUE THREAD

**Issue by lmx99** [AngaBlue/exe#7]
the assets config connot work   

"pkg": {
    "assets": [
      "assets/**/*"
    ],
    "targets": [
      "win"
    ],
    "outputPath": "../ai_layout"
  },

**Comment by TheBrunoRM** [comment]
They do work if you set the entry to "." or "./package.json", although the file becomes very large in size.

**Comment by AngaBlue** [comment]
Hi @lmx99 , do you have a minimal reproducible example to help me understand and fix this issue?
