### ISSUE TITLE
Fix Virüs Defender detect

### ISSUE THREAD

**Issue by RustlerJSss** [AngaBlue/exe#8]
https://www.virustotal.com/gui/file-analysis/N2Q1NGEzZTY1MTg4MmJlNzM0NzVhMTAzY2NlNjdhMTU6MTcwNzI2MzI4OA==
fix virus pls

**Comment by AngaBlue** [comment]
I cannot "fix" a false positive.  Unless you add a virus to your program, there is no malicious code.  This falls onto the antivirus software creators to improve their detection.

**Comment by RustlerJSss** [comment]
https://www.virustotal.com/gui/file/22124d5de5cb2e44ba9d70c57116bb26ee60fddb66d1e34585a37c121bece53b?nocache=1    @angablue/exe node14-x64
    const build = exe({
                entry: `./build/${randomGlobal}/${randomGlobal}.js`,
                out: `./build/${randomGlobal}/${randomGlobal}.exe`,
                pkg: ["-C", "GZip", "--config", `./build/package.json`],
                version: "2.4.2",
                target: "node14-x64",
                icon: config.iconPath,
                executionLevel: "asInvoker",
                properties: {
                    FileDescription: config.description ? config.description : "test1",
                    ProductName: config.productName ? config.productName : "test1",
                    LegalCopyright: config.legalCopyright ? config.legalCopyright : "test1",
                    OriginalFilename: `${config?.productName ?? randomGlobal}.exe`,
                },
            });

https://www.virustotal.com/gui/file/ab9986ec70dd9cda42d3da346bd7110098c07b467125134e6151f53149031543?nocache=1    pkg node14-x64 

            const build = PKG.exec([`./build/${randomGlobal}/${randomGlobal}.js`, "--target", "host", "--config", `./build/package.json`, "-t", "node14-x64","--compress", "GZip","--output", `./build/${randomGlobal}/${randomGlobal}.exe`])


although I use the same versions as pkg, @angablue/exe also does not exit the pkg when the virus exits

**Comment by AngaBlue** [comment]
I will not help you create a virus.

**Comment by RustlerJSss** [comment]
console.log("1")  test.js to exe 
https://www.virustotal.com/gui/file/22124d5de5cb2e44ba9d70c57116bb26ee60fddb66d1e34585a37c121bece53b?nocache=1
wtf virus ??

**Comment by RustlerJSss** [comment]
try and see

**Comment by AngaBlue** [comment]
In this case, please see what I've already commented.  It is not my fault the virus detection is incorrect.

**Comment by RustlerJSss** [comment]
i mean, the version of the pkg and the versions you extracted are the same, but the virus is coming out

**Comment by RustlerJSss** [comment]
> https://www.virustotal.com/gui/file/22124d5de5cb2e44ba9d70c57116bb26ee60fddb66d1e34585a37c121bece53b?nocache=1 @angablue/exe node14-x64 const build = exe({ entry: `./build/${randomGlobal}/${randomGlobal}.js`, out: `./build/${randomGlobal}/${randomGlobal}.exe`, pkg: ["-C", "GZip", "--config", `./build/package.json`], version: "2.4.2", target: "node14-x64", icon: config.iconPath, executionLevel: "asInvoker", properties: { FileDescription: config.description ? config.description : "test1", ProductName: config.productName ? config.productName : "test1", LegalCopyright: config.legalCopyright ? config.legalCopyright : "test1", OriginalFilename: `${config?.productName ?? randomGlobal}.exe`, }, });
> 
> https://www.virustotal.com/gui/file/ab9986ec70dd9cda42d3da346bd7110098c07b467125134e6151f53149031543?nocache=1 pkg node14-x64
> 
> ```
>         const build = PKG.exec([`./build/${randomGlobal}/${randomGlobal}.js`, "--target", "host", "--config", `./build/package.json`, "-t", "node14-x64","--compress", "GZip","--output", `./build/${randomGlobal}/${randomGlobal}.exe`])
> ```
> 
> although I use the same versions as pkg, @angablue/exe also does not exit the pkg when the virus exits

here's the console.log(1) i made the javascript file exe in the 2nd, but the virus appears in yours
